<template>
  <HomeLayout :narrow-feed="false">
    <div class="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <h1
        class="mb-6 border-b border-gray-200 pb-2 text-4xl font-bold text-gray-900 dark:border-neutral-800 dark:text-neutral-100"
      >
        Terms of Service
      </h1>

      <div class="space-y-6 text-gray-700 dark:text-neutral-300">
        <p>Last Updated: November 2025</p>

        <h2
          class="mt-6 text-2xl font-semibold text-gray-900 dark:text-neutral-100"
        >
          1. Acceptance of Terms
        </h2>
        <p class="text-sm">
          By accessing and using the
          {{ useRuntimeConfig().public.siteName }} platform, you accept and
          agree to be bound by the terms and provisions of this agreement. If
          you do not agree to abide by the above, please do not use this
          service.
        </p>

        <h2
          class="mt-6 text-2xl font-semibold text-gray-900 dark:text-neutral-100"
        >
          2. Seller Responsibilities
        </h2>
        <p class="text-sm">
          Sellers are responsible for the accuracy of their product listings,
          including images, stock levels, and ensuring that all products comply
          with local legal standards. Unauthorized use of copyrighted material
          or inaccurate thrift declarations may result in account suspension.
        </p>

        <h2
          class="mt-6 text-2xl font-semibold text-gray-900 dark:text-neutral-100"
        >
          3. Use of AI Content
        </h2>
        <p class="text-sm">
          Content generated by our AI tools (descriptions, captions, tags) is
          provided "as is." {{ useRuntimeConfig().public.siteName }} makes no
          warranty regarding the accuracy or legal compliance of AI-generated
          content. Sellers must review and approve all content before publishing
          to external platforms.
        </p>
      </div>
    </div>

    <!-- Right Sidebar -->
    <template #right-sidebar>
      <RightSideNavLinks />
    </template>
  </HomeLayout>
</template>

<script setup lang="ts">
import HomeLayout from '~/layouts/HomeLayout.vue'
import RightSideNavLinks from '~/layouts/children/RightSideNavLinks.vue'
</script>
